### ISSUE TITLE
Ревью тестового задания

### ISSUE THREAD

**Issue by Warboss-rus** [madGrant/todo-list-service#10]
- Странно, что MysqlDataProvider и MemoryDataProvider находятся на уровне Application и реализует интерфейс из Infrastructure. По чистой архитектуре слой App находится между доменом и инфраструктурой. Предлагаю DataProvider-ы выпилить, реализацию хранения перенести `в` репозитории в инфраструктуре, а сериализацию\десериализацию доменных объектов из массивов вынести в отдельный класс-гидратор
- То что сейчас лежит на слое Application - это скорее слои Presentation (Controller, Routing, View, Service) и Infrastructure (Bootstrap, Dependency, Repository). А вот Infrastructure/TaskService.php напоминает сервис Application.
- Все что лежит в Domain/Service по факту не является доменом (это интерфейсы и исключения которые никак не используются доменным слоем)
- (опционально) В идеале для чтения использовать отдельные query-модели и сервисы (принцип CQRS). Это поможет не только с производительностью (доменная модель частенько бывает тяжелой + обычно оборачивается транзакцией, локами и т.д.), но и позволит проводить чтение не боясь что-то сломать в доменной модели.
- В Domain для id лучше завести тип-обертку, чтобы не спутать его с другими int-ами и иметь возможность быстро поменять скажем на UUID-ы.
- такая генерация id-шников `$id = rand(0, 100);` может отстрелить ногу очень быстро, даже в тестах. Лучше возложить эту операцию на репозиторий, чтобы он проверял, что генерируемый id валидный и не используется
- странно выглядит `$this->request = $request::createFromGlobals();` (TodoList/Application/Controller/TaskApiController.php) - стоит либо инъектить запрос, либо создавать из глобалов, зачем и то и другое?
- смущает название класса TodoList\Application\View\TaskApiVew - обычно "View" - это модель для чтения, а не фабрика создания Response-ов
- необязательно заворачивать каждый вызов в отдельный try-catch в TodoList/Infrastructure/TaskService.php - достаточно общего блока (тем более что обработка исключений одинаковая)

Рекомендую почитать статьи по Clean Architecture (что-то типа [такого на английском](https://www.dandoescode.com/blog/clean-architecture-an-introduction/), либо если есть время книгу "Чистая архитектура. Искусство разработки программного обеспечения" Роберта Мартина)
Также можно посмотреть [видео по нашей архитектуре](https://www.youtube.com/watch?v=xT25xiKqPcI&ab_channel=iSpringTech)

**Comment by madGrant** [comment]
> Странно, что MysqlDataProvider и MemoryDataProvider находятся на уровне Application и реализует интерфейс из Infrastructure.

Да, я просто подходил к разбивке на слои, придерживаясь [Onion architecture](https://slides.silverfire.me/2017/phpfwday-ddd/layers.png), в ней по середине инфраструктурный уровень, а у вас принято делать по середине уровень приложения, ок. Я это исправлю.

> То что сейчас лежит на слое Application - это скорее слои Presentation (Controller, Routing, View, Service) и Infrastructure (Bootstrap, Dependency, Repository). А вот Infrastructure/TaskService.php напоминает сервис Application.

Да, если у меня поменять слои приложения и инфраструктуры, то станет больше походить на ваш подход.

> Все что лежит в Domain/Service по факту не является доменом (это интерфейсы и исключения которые никак не используются доменным слоем)

Если посмотреть схему на вашем [видео](https://www.youtube.com/watch?t=828&v=xT25xiKqPcI&feature=youtu.be), то на ней в Domain входят интерфейсы классов, которые напрямую работают с моделью, они должны быть на уровне Domain, а следующий слой уже будет их реализовать. Исключения в этой директории используются в интерфейсах, а значит составляют его часть.

> (опционально) В идеале для чтения использовать отдельные query-модели и сервисы (принцип CQRS).

Да, про CQRS я слышал, но выглядит как оверхед для этой задачи :) Постараюсь по возможности сделать.

>В Domain для id лучше завести тип-обертку, чтобы не спутать его с другими int-ами и иметь возможность быстро поменять скажем на UUID-ы.

Да, согласен. Интересно, алгоритм генерации id все же является частью модели или особенностью её реализации, в данной задаче?

> такая генерация id-шников $id = rand(0, 100); может отстрелить ногу очень быстро, даже в тестах. Лучше возложить эту операцию на репозиторий, чтобы он проверял, что генерируемый id валидный и не используется

Да, я понимаю, но такой id потом у меня нигде не сохраняется, поэтому его уникальность не имеет значение. Мне нужно просто лучше поработать над интерфейсом создания задачи, чтобы не делать такие хаки.

>странно выглядит $this->request = $request::createFromGlobals(); (TodoList/Application/Controller/TaskApiController.php) - стоит либо инъектить запрос, либо создавать из глобалов, зачем и то и другое?

Да, эта особенность здесь не нужна, забыл её убрать. Она имела смысл только для старой реализации моих тестов.

>смущает название класса TodoList\Application\View\TaskApiVew - обычно "View" - это модель для чтения, а не фабрика создания Response-ов

Да, обычно View отвечает за отображение, в данном случае отображение довольно вырожденное. Мне не принципиально, можно просто опустить этот термин и назвать класс фабрикой.

>необязательно заворачивать каждый вызов в отдельный try-catch в TodoList/Infrastructure/TaskService.php - достаточно общего блока (тем более что обработка исключений одинаковая)

Да, этот код стоит упростить.

### Итого: 

Фидбек, в целом, принимается, CQRS по ситуации.

**Comment by Warboss-rus** [comment]
> Да, я просто подходил к разбивке на слои, придерживаясь [Onion architecture](https://slides.silverfire.me/2017/phpfwday-ddd/layers.png), в ней по середине инфраструктурный уровень, а у вас принято делать по середине уровень приложения, ок. Я это исправлю.

У Вас странная картинка onion архитектуры. Быстрый поход в гугл выдает картинки ([1](https://www.codeguru.com/imagesvr_ce/2236/Onion1.png), [2](https://dzone.com/storage/temp/4436217-kolka.png), [3](https://herbertograca.files.wordpress.com/2017/03/2008-onion-architecture5.png)), где слой с сервисами находится в середине, а инфраструктура снаружи

> Если посмотреть схему на вашем [видео](https://www.youtube.com/watch?t=828&v=xT25xiKqPcI&feature=youtu.be), то на ней в Domain входят интерфейсы классов, которые напрямую работают с моделью, они должны быть на уровне Domain, а следующий слой уже будет их реализовать. Исключения в этой директории используются в интерфейсах, а значит составляют его часть.

В домене могут быть интерфейсы внешних сервисов, которые реализуются на внешних слоях, если эти сервисы необходимы для работы доменной логики. В данном случае эти сервисы не используются в домене. Что касается исключений, то ClientException и ServerException не выглядят как ошибки уровня домена, а значит им место на другом уровне абстракции

**Comment by madGrant** [comment]
> У Вас странная картинка onion архитектуры. Быстрый поход в гугл выдает картинки (1, 2, 3), где слой с сервисами находится в середине, а инфраструктура снаружи

Да, согласен, надо было чуть больше поресёчить.

>В домене могут быть интерфейсы внешних сервисов, которые реализуются на внешних слоях, если эти сервисы необходимы для работы доменной логики. В данном случае эти сервисы не используются в домене. Что касается исключений, то ClientException и ServerException не выглядят как ошибки уровня домена, а значит им место на другом уровне абстракции

Да, вы меня убедили.

**Comment by madGrant** [comment]
@Warboss-rus  я внес исправления, прошу проверить

**Comment by Warboss-rus** [comment]
Стало лучше, единственное создавать новые доменные сущности (в данном случае таски) - это задача не репозитория, а сервиса. Правда в этом случае возникают проблемы с id-шниками и приходится отказываться от генерируемых базой id-шников (к примеру использовать uuid-ы), либо при сохранении в репозиторий подставлять id-шник в объект. Для тестового задания сойдет и текущий вариант.

**Comment by madGrant** [comment]
Спасибо за обратную связь.
У меня были мысли создать фабрику для сущностей, но были вопросы, к какому слою её отнести. Плюс, тогда необходимо было бы сделать setId() для сущности, но в рамках доменной логики такого поведения нет, а подстраивать доменную сущность под поведение фабрик и репозиториев как-то неправильно. Возможно, если решать задачу совсем чисто, потребовался бы еще один dto.
Плюс, в текущей реализации меня смущает, что интерфейс репозитория у меня в доменной модели, а его реализация на уровне инфраструктуры, то есть связь между ними перепрыгивает уровень приложения, это выглядит неправильно.
